<a href="https://colab.research.google.com/github/swamyshravan/data-science-projects/blob/main/Artificial-Neural-Networks/ANN_example.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [29]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.7.0'

In [3]:
dataset = pd.read_csv('Churn_Modelling.csv')
x = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:,-1].values

In [4]:
print(y)

[1 0 1 ... 1 1 0]


In [5]:
print(x)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [6]:
from sklearn.preprocessing import LabelEncoder
le =LabelEncoder()
x[:,2] = le.fit_transform(x[:, 2])

In [7]:
print(x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [9]:
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [10]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state=0)

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [12]:
ann = tf.keras.models.Sequential()

In [13]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [14]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [15]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [16]:
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [17]:
ann.fit(x_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 0.5900 - accuracy: 0.7441
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4992 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4642 - accuracy: 0.8023
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4397 - accuracy: 0.8141
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4269 - accuracy: 0.8180
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4182 - accuracy: 0.8210
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4096 - accuracy: 0.8225
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3993 - accuracy: 0.8284
Epoch 9/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3887 - accuracy: 0.8360
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3777 - accura

In [18]:
print (ann.predict(sc.transform([[1,0,0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000 ]])) >0.5)

[[False]]


In [19]:
ypred = (ann.predict(x_test)>= 0.5)

In [20]:
print(ypred)

[[False]
 [False]
 [False]
 ...
 [False]
 [False]
 [False]]


In [21]:
yactual = y_test>0.5
print(yactual)

[False  True False ... False False False]


In [22]:
print(ypred.size)
print(yactual.size)

2000
2000


In [23]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(yactual, ypred)
print(cm)
cm1 = confusion_matrix(ypred, yactual)
print(cm1)

[[1523   72]
 [ 211  194]]
[[1523  211]
 [  72  194]]


In [24]:
confusion_matrix(y_test, ypred)

array([[1523,   72],
       [ 211,  194]])

In [25]:
(1548+142)/(1548+263+47+142)

0.845

In [26]:
(1548+263+47+142)

2000

In [27]:
(1548+142)/2000

0.845

In [28]:
(263+47)/2000

0.155